// ROOT ACTION CONSTANTS
export const USER_TOUCHED_SIDENAV = "rootReducer/USER_TOUCHED_SIDENAV";
export const VIDEO_HEIGHT = "rootReducer/VIDEO_HEIGHT";

// USER ACTION CONSTANTS
export const USER_LOGIN = "userReducer/USER_LOGIN";
export const USER_LOGIN_FAIL = "userReducer/USER_LOGIN_FAIL";
export const USER_LOGIN_LOADING = "userReducer/USER_LOGIN_LOADING";

export const USER_EVENT_LOADING = "UserEventLoading";
export const USER_EVENT_SUCCESS = "UserEventSuccess";
export const USER_EVENT_ERROR = "UserEventError";
export const USER_EVENT_UPDATE_STATE = "UserEventUpdateState";

export const TOGGLE_EVENT_CHAT = "ToggleEventChat";
export const TOGGLE_EVENT_NETWORKING = "ToggleEventNetworking";
export const UPDATE_EVENT_NETWORKING_DATA = "UPDATE_EVENT_NETWORKING_DATA";
export const PAUSE_CHAT_AND_PIN_MESSAGES_UPDATE =
  "PAUSE_CHAT_AND_PIN_MESSAGES_UPDATE";
export const WIPE_OFF_USER_REDUCER = "WIPE_OFF_USER_REDUCER";

// EVENT ACTION CONSTANTS
export const WIPE_OFF_EVENT_REDUCER = "WIPE_OFF_EVENT_REDUCER";

export const EVENT_MESSAGE_SUCCESS = "EVENT_MESSAGE_SUCCESS";
export const EVENT_MESSAGE_SUCCESS_MOBILE = "EVENT_MESSAGE_SUCCESS_MOBILE";
export const EVENT_MESSAGE_STATUS = "EVENT_MESSAGE_STATUS"
export const EVENT_MESSAGE_ADD_MORE = "EVENT_MESSAGE_ADD_MORE";
export const EVENT_MESSAGE_ERROR = "EVENT_MESSAGE_ERROR";
export const EVENT_MESSAGE_LOADING = "EVENT_MESSAGE_LOADING";

export const QUESTION_HIGHLIGHT_SUCCESS = "QUESTION_HIGHLIGHT_SUCCESS";
export const QUESTION_HIGHLIGHT_ERROR = "QUESTION_HIGHLIGHT_ERROR";
export const QUESTION_HIGHLIGHT_UPDATE = "QUESTION_HIGHLIGHT_UPDATE";
export const QUESTION_HIGHLIGHT_ADD_MORE = "QUESTION_HIGHLIGHT_ADD_MORE";
export const QUESTION_HIGHLIGHT_RESET_ALL = "QUESTION_HIGHLIGHT_RESET_ALL";
export const QUESTION_UPDATE_IS_VOTE = "QUESTION_UPDATE_IS_VOTE";

export const POLL_SUCCESS = "POLL_SUCCESS";
export const POLL_UPDATE = "POLL_UPDATE";
export const POLL_ERROR = "POLL_ERROR";
export const POLL_ADD_MORE = "POLL_ADD_MORE";
export const POLL_VOTE_OPTIONS_UPDATE = "POLL_VOTE_OPTIONS_UPDATE";

// SHARE HAND
export const SHAREHAND_SUCCESS = "SHAREHAND_SUCCESS";
export const SHAREHAND_UPDATE = "SHAREHAND_UPDATE";
export const SHAREHAND_ERROR = "SHAREHAND_ERROR";
export const SHAREHAND_ADD_MORE = "SHAREHAND_ADD_MORE";
export const SHAREHAND_SUBMIT_UPDATE = "SHAREHAND_SUBMIT_UPDATE";

// ADMIN ACTION CONSTANTS
export const ADMIN_GET_EVENTS_SUCCESS = "adminReducer/ADMIN_GET_EVENTS_SUCCESS";
export const ADMIN_GET_EVENTS_FAIL = "adminReducer/ADMIN_GET_EVENTS_FAIL";
export const ADMIN_GET_EVENTS_LOADING = "adminReducer/ADMIN_GET_EVENTS_LOADING";

export const ADMIN_GET_USERS_SUCCESS = "adminReducer/ADMIN_GET_USERS_SUCCESS";
export const ADMIN_GET_USERS_FAIL = "adminReducer/ADMIN_GET_USERS_FAIL";
export const ADMIN_GET_USERS_LOADING = "adminReducer/ADMIN_GET_USERS_LOADING";

export const WIPE_OFF_ADMIN_REDUCER = "adminReducer/WIPE_OFF_ADMIN_REDUCER";

// ADMIN PANEL

// USERS BY EVENT ACTION CONSTANTS
export const USERS_BY_EVENT_LOADING =
  "adminByEventReducer/USERS_BY_EVENT_LOADING";
export const USERS_BY_EVENT_FAILED =
  "adminByEventReducer/USERS_BY_EVENT_FAILED";
export const USERS_BY_EVENT_RESET = "adminByEventReducer/USERS_BY_EVENT_RESET";

export const GET_USERS_BY_EVENT_SUCCESS =
  "adminByEventReducer/GET_USERS_BY_EVENT_SUCCESS";
export const DELETE_USER_SUCCESS = "adminByEventReducer/DELETE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "adminByEventReducer/UPDATE_USER_SUCCESS";

export const WIPE_OFF_ADMIN_BY_EVENT_REDUCER =
  "adminByEventReducer/WIPE_OFF_ADMIN_BY_EVENT_REDUCER";
