export const foods = [
    { label: "Chicken", value: "chicken" },
    { label: "Fish", value: "fish" },
    { label: "Vegetarian", value: "vegetarian"},
  ]

export const Speciality = [
    { value: "Anaesthesiology", label: "Anaesthesiology" },
    { value: "Cardiology", label: "Cardiology" },
    { value: "Endocrinology", label: "Endocrinology" },
    { value: "Family Medicine / General Practice (GP)", label: "Family Medicine / General Practice (GP)" },
    { value: "Gastroenterology", label: "Gastroenterology" },
    { value: "General Surgery", label: "General Surgery" },
    { value: "Geriatric Medicine", label: "Geriatric Medicine" },
    { value: "Haematology", label: "Haematology" },
    { value: "Hand Surgery", label: "Hand Surgery" },
    { value: "Internal Medicine", label: "Internal Medicine" },
    { value: "Infectious Disease", label: "Infectious Disease" },
    { value: "Medical Oncology", label: "Medical Oncology" },
    { value: "Neurology", label: "Neurology" },
    { value: "Neurosurgery", label: "Neurosurgery" },
    { value: "Obstetrics & Gynaecology", label: "Obstetrics & Gynaecology" },
    { value: "Ophthalmology", label: "Ophthalmology" },
    { value: "Orthopaedic Surgery", label: "Orthopaedic Surgery" },
    { value: "Otorhinolaryngology", label: "Otorhinolaryngology" },
    { value: "Paediatric Medicine", label: "Paediatric Medicine" },
    { value: "Paediatric Surgery", label: "Paediatric Surgery" },
    { value: "Plastic Surgery", label: "Plastic Surgery" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Radiation Oncology", label: "Radiation Oncology" },
    { value: "Rehabilitation Medicine", label: "Rehabilitation Medicine" },
    { value: "Renal Medicine", label: "Renal Medicine" },
    { value: "Respiratory Medicine", label: "Respiratory Medicine" },
    { value: "Rheumatology", label: "Rheumatology" },
    { value: "Urology", label: "Urology" },
    { value: "Others", label: "Others" }]